[project]
name = "dspy-tutorials"
version = "0.1.0"
description = "Me coding along various DSPy tutorials"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=3.0.3",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
]
